CREATE TABLE "quizzes" (
  "id" varchar PRIMARY KEY,
  "title" varchar NOT NULL,
  "description" text NOT NULL,
  "type" smallint NOT NULL DEFAULT 1,
  "status" smallint NOT NULL DEFAULT 1,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quiz_id" varchar NOT NULL,
  "question_text" text NOT NULL,
  "time_limit" int NOT NULL DEFAULT 30
);

CREATE TABLE "answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "question_id" BIGINT NOT NULL,
  "answer_text" text NOT NULL,
  "is_correct" bool NOT NULL DEFAULT false
);

ALTER TABLE "questions" ADD FOREIGN KEY ("quiz_id") REFERENCES "quizzes" ("id");

ALTER TABLE "answers" ADD FOREIGN KEY ("question_id") REFERENCES "questions" ("id");
